apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  SUPABASE_URL: {{ .Values.secrets.SUPABASE_URL | quote }}
  SUPABASE_SERVICE_ROLE_KEY: {{ .Values.secrets.SUPABASE_SERVICE_ROLE_KEY | quote }}
